### ISSUE TITLE
convert epoch to timestamp

### ISSUE THREAD

**Issue by ronansalmon** [sni/grafana-thruk-datasource#1]
The time is in the epoch format (which grafana can't handle).

The problem seams to come from datasource.js:175,  col.type is empty when running the following request : 
xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/2/r/v1/downtimes"
params:Object
columns:"start_time,end_time,author,duration"
q:"host_name = 'test'"

The following dirty patch does the job for now : 

--- datasource.js.org	2019-01-04 16:55:13.269625067 +0100
+++ datasource.js	2019-01-04 16:48:09.672280018 +0100
@@ -175,7 +175,7 @@
                 _.map(result.data, function (d, i) {
                   var row = [];
                   table.columns.forEach(function (col) {
-                    if (col.type == "time") {
+                    if (/.*time.*/i.test(col.text)) {
                       row.push(d[col.text] * 1000);
                     } else {
                       row.push(d[col.text]);

Is there an other way of guessing the column type rather than looking for 'time' in the column's name ?

Thanks,
Ronan

**Comment by sni** [comment]
in "Column Styles" you can assign the type `Date`. But no idea if that type can be checked somehow.

**Comment by sni** [comment]
seems like we cannot access those types at that time of processing. I update the regular expression to match those fields as well.
