### ISSUE TITLE
Compatibility with thruk v2.30

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/grafana-thruk-datasource#2]
hi Sven,

Is this compatible with thrukv2.30, am having a datasource not connected: 403 Forbidden after upgrading thruk to version 2.30

**Comment by sni** [comment]
so it worked before the update?

**Comment by jgbuenaventura** [comment]
yes it is working on thruk v2.28

**Comment by sni** [comment]
i just tried and it works well with v2.30, can you provide a few details about the setup?

**Comment by jgbuenaventura** [comment]
hi Sven,

here's the grafana datasource

![image](https://user-images.githubusercontent.com/12998432/57937013-b0cd2380-78f7-11e9-8b53-526f29bae4be.png)

Here's the thruk v2.30-2 api 

![image](https://user-images.githubusercontent.com/12998432/57937060-c9d5d480-78f7-11e9-95c0-7c6c05a22bf7.png)

**Comment by jgbuenaventura** [comment]
10.0.102.172 - - [20/May/2019:11:50:37 +0200] "GET /thruk/r/v1/thruk?columns=rest_version HTTP/1.1" 403 161 "-" "Grafana/6.1.6"
10.0.102.172 - - [20/May/2019:11:51:16 +0200] "GET /thruk/r/v1/thruk?columns=rest_version HTTP/1.1" 403 161 "-" "Grafana/6.1.6"

**Comment by jgbuenaventura** [comment]
Hi Sven,

I manage to make it work now,

on the cgi.cfg of thruk i have to provide a user name in "default_user_name" field

 # DEFAULT USER
# Setting this variable will define a default user name that can
# access pages without authentication.  This allows people within a
# secure domain (i.e., behind a firewall) to see the current status
# without authenticating.  You may want to use this to avoid basic
# authentication if you are not using a secure server since basic
# authentication transmits passwords in the clear.
#
# Important:  Do not define a default username unless you are
# running a secure web server and are sure that everyone who has
# access to the CGIs has been authenticated in some manner!  If you
# define this variable, anyone who has not authenticated to the web
# server will inherit all rights you assign to this user!

default_user_name=thrukadmin

**Comment by sni** [comment]
i don't think thats a good idea, this will make all users thrukadmin if they are not authorized.

**Comment by jgbuenaventura** [comment]
so it would be better if i put a default_user_name with a less powerful access?

**Comment by jgbuenaventura** [comment]
hi sven,

i created a new thruk user called "thruk_exporter" an added it as a default_user_name. No other permission was given to the new user. If i dont put a value on default_user_name then i get an error on the grafana datasource.

**Comment by jgbuenaventura** [comment]
sorry dumb question, this settings seems to work

default_user_name=thruk_exporter

![image](https://user-images.githubusercontent.com/12998432/58158908-fd28b280-7cad-11e9-83cb-5c88c0110acf.png)
