### ISSUE TITLE
Error while populating dashboard variables from Thruk query

### ISSUE THREAD

**Issue by mr-scrawley** [sni/grafana-thruk-datasource#26]
Environment:
- thruk-datasource-plugin v2.0.0
- grafana v9.2.4

Attempting to to populate a dashboard variable as documented in 
https://github.com/sni/grafana-thruk-datasource/blob/d5c1a9f8ff199b70b275b05b688f389ff5831b1d/README.md?plain=1#L41-L48
results in a HTTP request that yields the following error from thruk:
``` json
{
   "code" : 400,
   "description" : "no datarow has a attribute named: column",
   "failed" : true,
   "help" : "lists livestatus hosts.\nsee https://www.naemon.org/documentation/usersguide/livestatus.html#hosts for details.",
   "message" : "possible typo in filter"
}
```

There seems to be a typo in
https://github.com/sni/grafana-thruk-datasource/blob/d5c1a9f8ff199b70b275b05b688f389ff5831b1d/src/datasource.ts#L74
Simply adding an `s` in the request URL (making it `&columns=`) seems to fix the issue. The rest of the script also seems to use plural here which is why I assume this is a typo and not an API change.

**Comment by sni** [comment]
Oh, that seems to be a typo indeed. Could you create a small pull request? Then you would get credits you deserve :-)

**Comment by sni** [comment]
thanks, should be fine again with the v2.0.1
