### ISSUE TITLE
Variable expansion for repeated panels (or rows) not handled correctly

### ISSUE THREAD

**Issue by mr-scrawley** [sni/grafana-thruk-datasource#27]
Environment:
- thruk-datasource-plugin v2.0.0
- grafana v9.2.4

I'm trying to [repeat a row or panel](https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/create-dashboard/#configure-repeating-rows) based on a dashboard variable using a query based on a thruk-datasource.
The behavior in previous versions used to be that referencing the variable in the request (e.g. `$VARIABLE`) led to one request containing one value of the variable for one panel instance. This was repeated for every selected value.

The behavior I'm seeing in the environment above is that as soon as two or more (or all) values are selected in the dashboard variable header,  every single request contains a comma-separated list of all selected values.
That would make sense if it was possible to pool all requests into one combined request for the whole dashboard, which does not seem the case as:

1.  The return value is empty for my case (`FROM /hosts/$HOST/services`).
2.  That request containing the list of values is repeated for every selected value.

Originally I assumed that this was a problem with grafana as I thought that the plugin would process the already expanded variable. After experimenting with similar scenarios with different datasources, I wasn't able to replicate the issue, however.

**Comment by sni** [comment]
Do you have a simple example dashboard showing this issue? Then i could replicate it in my dev system and hopefully find a quick fix.

**Comment by mr-scrawley** [comment]
> Do you have a simple example dashboard showing this issue? Then i could replicate it in my dev system and hopefully find a quick fix.

The following is an example dashboard using repetition to list `/hosts/$Host/services` for the selected values of `Host` (you'll have to change the values to ones that are present in your dev Thruk instance).

The exact same dashboard works under Grafana v8.3.4 and thruk-datasource-plugin 1.0.6 where the request is repeated using individual values instead of multiple requests using a concatenated list of values as in the current version.

Again, I am not sure this is a plugin issue but I wasn't able to replicate the issue for other datasources.

I wasn't able to attach a json and didn't want to attach an archive, so I've just embedded it here:
<details><summary>Dashboard JSON</summary>

```JSON
{
  "__inputs": [
    {
      "name": "DS_THRUK",
      "label": "Thruk",
      "description": "",
      "type": "datasource",
      "pluginId": "sni-thruk-datasource",
      "pluginName": "Thruk"
    }
  ],
  "__elements": {},
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "9.2.4"
    },
    {
      "type": "datasource",
      "id": "sni-thruk-datasource",
      "name": "Thruk",
      "version": "2.0.0"
    },
    {
      "type": "panel",
      "id": "table",
      "name": "Table",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "sni-thruk-datasource",
        "uid": "${DS_THRUK}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": "auto",
            "displayMode": "auto",
            "inspect": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 16,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "footer": {
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "showHeader": true
      },
      "pluginVersion": "9.2.4",
      "repeat": "Host",
      "repeatDirection": "h",
      "targets": [
        {
          "columns": [
            "*"
          ],
          "condition": "",
          "datasource": {
            "type": "sni-thruk-datasource",
            "uid": "${DS_THRUK}"
          },
          "refId": "A",
          "table": "/hosts/$Host/services",
          "type": "table"
        }
      ],
      "title": "Services Table",
      "type": "table"
    }
  ],
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": true,
          "text": [
            "All"
          ],
          "value": [
            "$__all"
          ]
        },
        "hide": 0,
        "includeAll": true,
        "multi": true,
        "name": "Host",
        "options": [
          {
            "selected": true,
            "text": "All",
            "value": "$__all"
          },
          {
            "selected": false,
            "text": "host1",
            "value": "host1"
          },
          {
            "selected": false,
            "text": "host2",
            "value": "host2"
          }
        ],
        "query": "host1, host2",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "repetition bug example",
  "uid": "-ZdzxoOVk",
  "version": 1,
  "weekStart": ""
}
```
</details>

**Comment by sni** [comment]
Thanks, this makes it easier to reproduce.
And well, if it worked before, it should work with this version as well. I might just have missed something while rewriting the module.
