### ISSUE TITLE
filters at customer vars error

### ISSUE THREAD

**Issue by jgbuenaventura** [sni/grafana-thruk-datasource#3]
Hi Sven,

We are getting this error, when filtering the custom variables.
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/8/r/v1/services",
    "params": {
      "columns": [
        "count(state)",
        "state"
      ],
      "q": "display_name ~ 'service_3rd_Puppet_Agent' and _HOSTCOUNTRY ~ ^(AN)$"
    }
  },
  **"response": {
    "code": 500,
    "description": "parse error at ^(AN)$ at /usr/share/thruk/lib/Thruk/Utils/Status.pm line 2496.\n",
    "failed": true,
    "message": "error during request"**
  }                                      
}

![image001](https://user-images.githubusercontent.com/12998432/58871458-99ae7400-86f4-11e9-821d-39892d25dab3.png)

**Comment by sni** [comment]
sorry, somehow missed this one. Could it be that you simply missed quotes around the $country?
