### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by welj** [sni/grafana-thruk-datasource#38]
Hi,
all time error :

Datasource error: 404 Not Found

![image](https://github.com/sni/grafana-thruk-datasource/assets/5948085/137017b9-492d-4613-ae8a-589610486ea4)

can help debug? ;)

test site is ok

![image](https://github.com/sni/grafana-thruk-datasource/assets/5948085/32c222ff-c458-4043-b3c9-84ec65b6314f)

**Comment by welj** [comment]
sorry my bad, used old thruk.conf for apache

Now its work :) have nice day -_- thx for soft

**Comment by sni** [comment]
no worries, glad to hear it's working now...
