### ISSUE TITLE
filter with timestamp comparison

### ISSUE THREAD

**Issue by jbeaujour** [sni/grafana-thruk-datasource#4]
Hello,
I try to reproduce a thruk query sucj like this where i can filter services with last_check older :
thruk r '/services?columns=last_check,description&last_check[lt]=-5d' 
with grafana i cant use the same syntax 
"=" is OK
">" is ?
but not "<" 
Is that an issue or a mistake with me ;)
Thruk 2.30-2 and datasource 1.0.3 and grafana 6.2.5
Thank's

**Comment by sni** [comment]
i don't really get the question? Also please always use the latest stable release, especially the rest api has improved a lot lately.

**Comment by jbeaujour** [comment]
Hello
how to do this "QUERY":
'SELECT display_name FROM services WHERE "last-check" < now -7d'
I succeeded by creating a dashboard variable in GRAFANA.
$thruk_7d = select UNIX_TIMESTAMP () - 604800
and then create the QUERY with the thruk datasource like this:
'SELECT display_name FROM /services WHERE last_check < "$thruk_7d"'
do you see a simpler option?

thank you

**Comment by sni** [comment]
Should be possible with the next Thruk release or tomorrows nightly.
The correct syntax would be:

```
SELECT display_name FROM services WHERE last-check < "now -7d"
```
