### ISSUE TITLE
Bug: SELECT C:\ not working

### ISSUE THREAD

**Issue by lgmu** [sni/grafana-thruk-datasource#43]
Querying a nsclient disk check which has performance metrics like "C:\ used" and "C:\ used %" is currently not possible, except when using 
```SELECT * ...```
and then using grafana transformations. It works but it's not fun or user friendly.

It would be nice if 
```SELECT host_name, C:\ used % FROM /services WHERE ...```
works :)

Thanks

**Comment by sni** [comment]
implemented with https://github.com/sni/Thruk/commit/28d377f7aae588e9cee1814333af7537c7abe4dc
