### ISSUE TITLE
Feature request: SELECT count(*) AS < value >

### ISSUE THREAD

**Issue by lgmu** [sni/grafana-thruk-datasource#44]
It would be nice to be able to use
```SELECT count(*) AS < value > from /services where ...```

Then < value > could be displayed in a Bar gauge for example, without having to use an override as shown below:

![image](https://github.com/sni/grafana-thruk-datasource/assets/80966566/1214d216-c5ce-4620-aec3-26ef8b7aa41d)

Here I'm querying the plugin_output and want to count how many services have "SQL Server 2022" in the output.
![image](https://github.com/sni/grafana-thruk-datasource/assets/80966566/8d149046-12d7-4d1a-af5e-30ac48fd51dd)

Currently the only workaround is to use Overrides:
![image](https://github.com/sni/grafana-thruk-datasource/assets/80966566/8a6d9d57-1d93-4457-995f-16a9531e3544)

I also can't re-use count(*) in multiple queries, because then it would just show a single time in the Overrides. So to avoid that, you need to count different attributes

**Comment by sni** [comment]
`SELECT count(*) AS name from /services` should work as expected now.

**Comment by sni** [comment]
fixed in https://github.com/sni/Thruk/commit/811ea2bf186f7318e521a75b9b13b3eac493c67c
