### ISSUE TITLE
Feature request: Select Upper/Lowercase 

### ISSUE THREAD

**Issue by lgmu** [sni/grafana-thruk-datasource#45]
Would be great if something like

`SELECT upper(host_name) FROM /services`

worked.

Additional ideas:

- uppercase
- lowercase
- list_as_rows (for hostgroups which are stored in an array)

**Comment by sni** [comment]
implemented with https://github.com/sni/Thruk/commit/e4fb3a19969fa76e736360e15bffa829781ae75d
