### ISSUE TITLE
Display Host Comments

### ISSUE THREAD

**Issue by Tots69** [sni/grafana-thruk-datasource#8]
Hello,

I'm looking for a way to display Host Comments or Host Downtime Comments.
I only find the way to display the Host comment ID.
Is it possible to show those informations ?

Regards,

**Comment by sni** [comment]
Depends on how you want to show it. If it's for a specific host, you have to query the downtimes or comments table.
Right now it is not possible to join that information in a host query.

**Comment by Tots69** [comment]
I would like to have a grafana table with Hostname, host state, plugin output, host comments or host downtime if exists.
I try a lot of things found but I don't get the result I'm looking for.
Do you think it's possible to have this render ?
